# Generated by Django 4.0.5 on 2022-06-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='calendar_id',
            new_name='calendar',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('WR', 'Работа'), ('LR', 'Учёба')], default='LR', max_length=2),
        ),
    ]
