# Generated by Django 4.0.5 on 2022-06-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0003_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('WR', 'Работа'), ('RL', 'Отдых')], default='RL', max_length=2),
        ),
    ]
